apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  completions: 3
  completionMode: Indexed
  parallelism: 3
  template:
    spec:
      containers:
        - image: busybox
          imagePullPolicy: IfNotPresent
          name: busybox-sleep
          command: ["sh", "-c", "trap exit INT TERM; sleep 1m & wait"]
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
      restartPolicy: OnFailure
