apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox-sleep
        command: ['sh', '-c', 'trap exit INT TERM; sleep 1m & wait']
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 1
      restartPolicy: Always
