apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  generateName: job-
  namespace: default
  labels:
    for: test
spec:
  runPolicy:
    backoffLimit: 0
    schedulingPolicy:
      queue: test
      priorityClass: high-priority
  pytorchReplicaSpecs:
    Master:
      replicas: 1 # must be 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - image: busybox:1.37.0-glibc
              imagePullPolicy: IfNotPresent
              name: pytorch # must be `pytorch`
              command: ["sh", "-c", "trap exit INT TERM; sleep 30s & wait"]
              resources:
                limits:
                  cpu: "1"
                  memory: "100Mi"
                  nvidia.com/gpu: "1"
    Worker:
      replicas: 5
      restartPolicy: Never
      template:
        spec:
          containers:
            - image: busybox:1.37.0-glibc
              imagePullPolicy: IfNotPresent
              name: pytorch # must be `pytorch`
              command: ["sh", "-c", "trap exit INT TERM; sleep 30s & wait"]
              resources:
                limits:
                  cpu: "1"
                  memory: "100Mi"
                  nvidia.com/gpu: "1"
