apiVersion: v1
kind: Secret
metadata:
  name: csi-static-secret
  namespace: default
stringData:
  userID: csi-static
  userKey: AQACJetpyvjeDBAAvHBRzZEaGgE4UKhoJLN1Hg==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-static-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: csi-static-secret
      namespace: default
    volumeAttributes:
      # optional file system to be mounted
      "fsName": "cephfs"
      "clusterID": "990b5070-3964-11f1-8888-476de7d3e05c"
      "staticVolume": "true"
      "rootPath": /volumes/csi/static_vol/26d36559-7994-47b5-9bde-78ec34486754
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: csi-static-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
