apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-ceph-pv-po
spec:
  restartPolicy: OnFailure
  containers:
    - name: app
      image: busybox:1.37.0-glibc
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "trap exit INT TERM; sleep infinity & wait"]
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc
