apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    kai.scheduler/queue: test
spec:
  restartPolicy: OnFailure
  schedulerName: kai-scheduler
  containers:
    - image: busybox:1.37.0-glibc
      imagePullPolicy: IfNotPresent
      name: sleep-busybox
      command: ["sh", "-c", "trap exit INT TERM; sleep 1m & wait"]
      resources:
        requests:
          cpu: "1"
          memory: 100Mi
        limits:
          cpu: "1"
          memory: 100Mi
