apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sleep
spec:
  serviceName: sleep-service
  replicas: 3
  selector:
    matchLabels:
      app: sleep
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: sleep
    spec:
      restartPolicy: Always
      containers:
      - image: busybox:1.37.0-glibc
        imagePullPolicy: IfNotPresent
        name: sleep-busybox
        command: ["sh", "-c", "trap exit INT TERM; sleep 1m & wait"]
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
          limits:
            cpu: "1"
            memory: 100Mi
