apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: sleep
spec:
  minAvailable: 3
  schedulerName: volcano
  priorityClassName: high-priority
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
  - replicas: 3
    name: sleep-task
    policies:
    - event: TaskCompleted
      action: CompleteJob
    template:
      spec:
        restartPolicy: Never
        containers:
        - image: busybox:1.37.0-glibc
          imagePullPolicy: IfNotPresent
          name: sleep-busybox
          command: ["sh", "-c", "trap exit INT TERM; sleep 1m & wait"]
          resources:
            requests:
              cpu: "1"
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 100Mi
