apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: las0
  share: /srv/nfs
  mountPermissions: "0777"
volumeBindingMode: Immediate
allowVolumeExpansion: true
