apiVersion: kueue.x-k8s.io/v1alpha1
kind: Topology
metadata:
  name: default
spec:
  levels:
  - nodeLabel: topology-block
  - nodeLabel: topology-rack
  - nodeLabel: kubernetes.io/hostname
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
spec:
  nodeLabels:
    node-group: default
  topologyName: default
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: test
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    - pods
    flavors:
    - name: default
      resources:
      - name: cpu
        nominalQuota: 8
      - name: memory
        nominalQuota: 64Gi
      - name: pods
        nominalQuota: 4
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: default
  name: test
spec:
  clusterQueue: test
